title: Sourcegraph
email: hi@sourcegraph.com
description: >
  How developers discover and understand code. Sourcegraph is a fast, global, semantic code search and cross-reference engine.
baseurl: ""
url: "https://about.sourcegraph.com"
twitter_username: srcgraph
twitter_image: /assets/images/sourcegraph-mark.png
github_username:  sourcegraph
encoding: utf-8

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md