title: Sourcegraph
email: hi@sourcegraph.com
description: >
  How developers discover and understand code. Sourcegraph is a fast, global, semantic code search and cross-reference engine.
baseurl: ""
url: "http://calm-whale.cloudvent.net"
twitter_username: srcgraph
twitter_image: /assets/images/sourcegraph-mark.png
github_username:  sourcegraph
encoding: utf-8
permalink: /blog/:title/

paginate: 11
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md